-- This script provides a consolidated, idempotent setup for the entire
-- Project Canvas database schema, including tables, roles, policies,
-- and storage. Running this script on a fresh Supabase project will
-- configure it completely.

-- =================================================================
-- Table Definitions
-- =================================================================

-- Create profiles table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  role text default 'user',
  theme text default 'light',
  image_generations_count integer not null default 0,
  text_generations_count integer not null default 0,
  uploads_count integer not null default 0
);
comment on table public.profiles is 'Public user profiles, linked to auth.users.';
comment on column public.profiles.id is 'References auth.users.id';
comment on column public.profiles.role is 'User role, e.g., ''admin'' or ''user''';
comment on column public.profiles.theme is 'User preferred theme, e.g., ''light'' or ''dark''';

-- Create pins table
create table if not exists public.pins (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users on delete cascade not null,
  image_url text not null,
  position jsonb not null default '{"x": 0, "y": 0}',
  notes text,
  is_deleted boolean default false not null
);
comment on table public.pins is 'Stores all the pins for the pinboard.';
comment on column public.pins.position is 'Stores the {x, y} coordinates of the pin.';

-- Create files table
create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pin_id uuid references public.pins on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  file_name text not null,
  storage_path text not null
);
comment on table public.files is 'Stores metadata for files attached to pins.';

-- Create connections table
create table if not exists public.connections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    start_pin_id UUID REFERENCES public.pins(id) ON DELETE CASCADE NOT NULL,
    end_pin_id UUID REFERENCES public.pins(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
comment on table public.connections is 'Stores connections (lines) between pins.';

-- Create storylines table
create table if not exists public.storylines (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
comment on table public.storylines is 'Stores storyline narratives created by users.';

-- Create storyline_pins joining table
create table if not exists public.storyline_pins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storyline_id uuid REFERENCES public.storylines(id) ON DELETE CASCADE NOT NULL,
    pin_id uuid REFERENCES public.pins(id) ON DELETE CASCADE NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE NOT NULL,
    position JSONB NOT NULL DEFAULT '{"x": 0, "y": 0}'
);
comment on table public.storyline_pins is 'Joins pins to storylines, defining their position and completion status.';
comment on column public.storyline_pins.position is 'Stores the {x, y} coordinates of the pin within the storyline canvas.';

-- =================================================================
-- Functions and Triggers
-- =================================================================

-- Function to get the role of the currently authenticated user
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT role
    FROM public.profiles
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if the currently authenticated user is an admin.
-- Using a SECURITY DEFINER function is more performant than per-row subqueries in RLS policies.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to create a profile for a new user automatically
-- and assign 'admin' role to the first user.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  is_first_user BOOLEAN;
  -- Define the default instruction templates
    instagram_instructions TEXT := 'A photorealistic and visually stunning image of [SUBJECT]. The style is minimalist and educational, with dramatic, high-contrast lighting and a clean, focused composition. The image must be a 1080x1350px vertical portrait.';

    tiktok_instructions TEXT := 'An energetic and vibrant vertical image of [SUBJECT], suitable for TikTok. The style is bold with a clear focal point, high-contrast colors, and dynamic lighting. The image must be in a 9:16 vertical format (1080x1920px).';
BEGIN
  -- Create the user''s public profile
  INSERT INTO public.profiles (id, full_name, avatar_url, role, theme)
  VALUES (NEW.id, NEW.raw_user_meta_data->>''full_name'', NEW.raw_user_meta_data->>''avatar_url'', ''user'', ''light'');

  -- Insert the default Instagram instruction profile for the new user
  INSERT INTO public.model_instructions (user_id, profile_name, instructions)
  VALUES (NEW.id, 'Instagram Image Default', instagram_instructions);

  -- Insert the default TikTok instruction profile for the new user
  INSERT INTO public.model_instructions (user_id, profile_name, instructions)
  VALUES (NEW.id, 'Tiktok Image Default', tiktok_instructions);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to increment a user's image generation count
-- Function to increment a user's image generation count, excluding admin users.
CREATE OR REPLACE FUNCTION public.increment_image_count(user_id_param uuid)
RETURNS void AS $$
  UPDATE public.profiles
  SET image_generations_count = image_generations_count + 1
  WHERE id = user_id_param AND (SELECT role FROM public.profiles WHERE id = user_id_param) != 'admin';
$$ LANGUAGE sql;

-- Function to increment a user's text generation count, excluding admin users.
CREATE OR REPLACE FUNCTION public.increment_text_count(user_id_param uuid)
RETURNS void AS $$
  UPDATE public.profiles
  SET text_generations_count = text_generations_count + 1
  WHERE id = user_id_param AND (SELECT role FROM public.profiles WHERE id = user_id_param) != 'admin';
$$ LANGUAGE sql;

-- Function to increment a user's upload count, excluding admin users.
CREATE OR REPLACE FUNCTION public.increment_uploads_count(user_id_param uuid)
RETURNS void AS $$
  UPDATE public.profiles
  SET uploads_count = uploads_count + 1
  WHERE id = user_id_param AND (SELECT role FROM public.profiles WHERE id = user_id_param) != 'admin';
$$ LANGUAGE sql;


-- Trigger to execute the function after a new user is created
-- Drop trigger if it exists to make the script idempotent
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =================================================================
-- Row Level Security (RLS)
-- =================================================================

-- Enable RLS for all tables
alter table public.profiles enable row level security;
alter table public.pins enable row level security;
alter table public.files enable row level security;
alter table public.connections enable row level security;
alter table public.storylines enable row level security;
alter table public.storyline_pins enable row level security;

-- Policies for: public.profiles
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);

drop policy if exists "Users can insert their own profile." on public.profiles;
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Users can update their own profile." on public.profiles;
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

-- Policies for: public.pins
-- PINS RLS POLICIES
-- First, drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Enable select for authenticated users only" ON public.pins;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.pins;
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON public.pins;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.pins;
DROP POLICY IF EXISTS "Users see own pins; Admins see all." ON public.pins;
DROP POLICY IF EXISTS "Users can insert their own pins." ON public.pins;
DROP POLICY IF EXISTS "Users can update their own pins, and admins can update any." ON public.pins;
DROP POLICY IF EXISTS "Admins can delete any pin." ON public.pins;
DROP POLICY IF EXISTS "Enable select for users or admins" ON public.pins;
DROP POLICY IF EXISTS "Enable update for users or admins" ON public.pins;
DROP POLICY IF EXISTS "Enable delete for users or admins" ON public.pins;


-- --- THIS IS THE FIX ---
DROP POLICY IF EXISTS "Users can only view their own pins." ON public.pins;
DROP POLICY IF EXISTS "Users can only view their own non-deleted pins." ON public.pins;

-- 1. SELECT Policy: A user can only see non-deleted pins that belong to them.
CREATE POLICY "Users can only view their own non-deleted pins." ON public.pins
FOR SELECT USING (auth.uid() = user_id AND is_deleted = false);

-- 2. INSERT Policy: Users can create their own pins.
CREATE POLICY "Users can insert their own pins." ON public.pins
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. UPDATE Policy: Users can only update their own pins.
CREATE POLICY "Users can update their own pins." ON public.pins
FOR UPDATE USING (auth.uid() = user_id);

-- 4. DELETE Policy: Users can only delete their own pins.
CREATE POLICY "Users can delete their own pins." ON public.pins
FOR DELETE USING (auth.uid() = user_id);
-- --- END OF FIX ---

-- Policies for: public.files
drop policy if exists "Users can view files for pins they can access." on public.files;
create policy "Users can view files for pins they can access." on public.files for select using (exists (select 1 from public.pins where pins.id = files.pin_id));

drop policy if exists "Users can insert files for their own pins." on public.files;
create policy "Users can insert files for their own pins." on public.files for insert with check (auth.uid() = user_id and exists (select 1 from public.pins where pins.id = files.pin_id and pins.user_id = auth.uid()));

drop policy if exists "Users can delete their own files." on public.files;
create policy "Users can delete their own files." on public.files for delete using (auth.uid() = user_id);

-- Policies for: public.connections
drop policy if exists "All users can view all connections." on public.connections;
create policy "All users can view all connections." on public.connections for select using (auth.role() = 'authenticated');

drop policy if exists "Users can insert their own connections." on public.connections;
create policy "Users can insert their own connections." on public.connections for insert with check (auth.uid() = user_id);

drop policy if exists "Admins can delete any connection." on public.connections;
create policy "Admins can delete any connection." on public.connections for delete using (public.is_admin());

-- Policies for: public.storylines
drop policy if exists "Users can view their own storylines." on public.storylines;
create policy "Users can view their own storylines." on public.storylines for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own storylines." on public.storylines;
create policy "Users can insert their own storylines." on public.storylines for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own storylines." on public.storylines;
create policy "Users can update their own storylines." on public.storylines for update using (auth.uid() = user_id);

drop policy if exists "Users can delete their own storylines." on public.storylines;
create policy "Users can delete their own storylines." on public.storylines for delete using (auth.uid() = user_id);

-- Policies for: public.storyline_pins
drop policy if exists "Users can view pins in their own storylines." on public.storyline_pins;
create policy "Users can view pins in their own storylines." on public.storyline_pins for select using (exists (select 1 from public.storylines where storylines.id = storyline_pins.storyline_id and storylines.user_id = auth.uid()));

drop policy if exists "Users can insert pins into their own storylines." on public.storyline_pins;
create policy "Users can insert pins into their own storylines." on public.storyline_pins for insert with check (exists (select 1 from public.storylines where storylines.id = storyline_pins.storyline_id and storylines.user_id = auth.uid()));

drop policy if exists "Users can update pins in their own storylines." on public.storyline_pins;
create policy "Users can update pins in their own storylines." on public.storyline_pins for update using (exists (select 1 from public.storylines where storylines.id = storyline_pins.storyline_id and storylines.user_id = auth.uid()));

drop policy if exists "Users can delete pins from their own storylines." on public.storyline_pins;
create policy "Users can delete pins from their own storylines." on public.storyline_pins for delete using (exists (select 1 from public.storylines where storylines.id = storyline_pins.storyline_id and storylines.user_id = auth.uid()));

-- =================================================================
-- Storage Policies
-- Note: Buckets must be created manually in the Supabase UI first.
-- 1. 'images' (Public)
-- 2. 'documents' (Private)
-- =================================================================

-- Policies for: storage.objects (bucket: images)
drop policy if exists "Images are publicly viewable" on storage.objects;
create policy "Images are publicly viewable" on storage.objects for select using ( bucket_id = 'images' );

drop policy if exists "Authenticated users can upload images" on storage.objects;
create policy "Authenticated users can upload images" on storage.objects for insert with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

drop policy if exists "Users can update their own images" on storage.objects;
create policy "Users can update their own images" on storage.objects for update using ( auth.uid() = owner and bucket_id = 'images' );

drop policy if exists "Users can delete their own images" on storage.objects;
create policy "Users can delete their own images" on storage.objects for delete using ( auth.uid() = owner and bucket_id = 'images' );

-- Policies for: storage.objects (bucket: documents)
drop policy if exists "Users can view documents for accessible pins" on storage.objects;
create policy "Users can view documents for accessible pins" on storage.objects for select using (bucket_id = 'documents' and exists (select 1 from public.files where files.storage_path = storage.objects.name and exists (select 1 from public.pins where pins.id = files.pin_id)));

drop policy if exists "Authenticated users can upload documents" on storage.objects;
create policy "Authenticated users can upload documents" on storage.objects for insert with check ( bucket_id = 'documents' and auth.role() = 'authenticated' );

drop policy if exists "Users can update their own documents" on storage.objects;
create policy "Users can update their own documents" on storage.objects for update using ( auth.uid() = owner and bucket_id = 'documents' );

drop policy if exists "Users can delete their own documents" on storage.objects;
create policy "Users can delete their own documents" on storage.objects for delete using ( auth.uid() = owner and bucket_id = 'documents' );

-- Create generation_jobs table
CREATE TABLE IF NOT EXISTS public.generation_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    anchor_pin_id UUID REFERENCES public.pins(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, processing, completed, failed
    job_type TEXT NOT NULL, -- 'ai_prompt' or 'url'
    source_content TEXT NOT NULL, -- The AI prompt or the image URL
    note_text TEXT,
    pin_position JSONB,
    related_instruction_id UUID REFERENCES public.model_instructions(id),
    error_message TEXT
);

-- Enable RLS for the new table
ALTER TABLE public.generation_jobs ENABLE ROW LEVEL SECURITY;

-- Policies for: public.generation_jobs
CREATE POLICY "Users can manage their own generation jobs"
ON public.generation_jobs
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
